### PR TITLE
Simplify sending and return users from the brain

### PR DESCRIPTION
**Pull request by awiddersheim**
The Hubot Hipchat adapter uses the `envelope.user.reply_to` property as
the primary way for determining where a message should get sent. This
does not appear to be necessary. It is an abnormal pattern that doesn't
seem to be in any other popular adapters (Slack, Campfire). Perhaps this
was necessary on some older versions of Hubot and was never updated.

The `envelope.room` property seems to have all it needs to send the
message to the right place. Removing the `reply_to` logic simplifies
things quite a bit. This change also helps with #175 where messages
would get sent to the wrong origins for some long running processes if
the user happens to send a message in another room before the process
can finish.

The fix for the above problem in #207 broke the brain some. Typically,
in other adapters, the `message.user` object returned will be a
reference to the brain. Here, you can store data that you would want to
persist. By cloning this object it breaks that ability and can affect
plugins expecting that behavior.

Found this issue while working with the `hubot-pager-me` plugin. This
plugin assumes the `message.user` property is from the brain. When
doing things like `pager me as foo@bar.com` it assigns it to that
property where it should persist but does not. This does work in other
adapters though like Shell and Campfire.

Finally, one other added benefit these changes bring are a level of
consistency to the `user.room` property. When `changePresence()` was
called it would populate the brain and set the room to the JID version
which looks something like `108300_foo_bar@conf.hipchat.com`. When a
message was getting handled it would filter the room through
`roomNameFromJid()` which would transform the room name to a friendlier
format like `foo_bar`. Now, the `user.room` property will always bet set
to the JID version.

### CODE REVIEW

**Comment by mattdeboard** [comment]
I enthusiastically 👍 this pull request.

**Comment by rclayton-the-terrible** [comment]
This PR fixed an issue we were having where user info was completely unavailable to us (reply_to referenced the room and not the user).

**Comment by mattdeboard** [comment]
I think it's probably safe to say this repo is dead

**Comment by rclayton-the-terrible** [comment]
@mattdeboard this isn't maintained by Atlassian?  If not, one more reason to go to Slack...

**Comment by eduponte** [comment]
👍 the PR. Seems like @powdahound was involved in HipChat and Atlassian, but no activity here since June 2014.

**Comment by eduponte** [comment]
... and so seems to be @rbergman too, and there's recent activity by him. Let's hope this is not dead.

**Comment by rbergman** [comment]
Hi folks, please see this comment for more information:

https://github.com/hipchat/hubot-hipchat/pull/280#issuecomment-243485123

**Comment by Wilfred** [comment]
Note that this will affect any plugins using the old approach to get the JID. Previously the only way to get the topic was:

```coffee-script
# Get the topic of the current room. Hubot doesn't expose a convenient
# API for this, so look it up on the connector.
getTopic = (robot, msg, cb) ->
  roomJid = msg.envelope.user.reply_to

  robot.adapter.connector.getRooms (err, rooms, stanza) ->
    roomDetails = _.find rooms, {'jid': roomJid}
    if roomDetails
      cb roomDetails.topic
    else
      # Handle private 1-1 conversations robustly.
      cb null
```

I'm aware that Hubot exposes a way of being notified when the topic changes, but it was more convenient to be able to look up the topic at a point in time.

**Pull request merged**
