### PR TITLE
Upgrade node-xmpp (fixed compilation hell)

### PR DESCRIPTION
**Pull request by mal**
The new version solves the previous compilation problems, and limits the dependency tree to just the necessary subset of the `node-xmpp` suite (drops the implicit dependency on the server and component libs).

This also removes the need for the custom loader as there are now no messages to suppress.

~~It's still alpha at the moment, so I completely understand if you don't want to merge it at this time. I decided to PR it now anyway as it made our lives much easier, and might be of use to others until `node-xmpp` ship their `1.0`.~~

### CODE REVIEW

**Comment by raespinosa** [comment]
Had to upgrade it as well in #214 . The new version allows an http-endpoint useful for deploying hubot inside a firewalled network.

**Comment by cycomachead** [comment]
:+1: 

Currently needing to use a fork of this for the same reason.

**Comment by mal** [comment]
Further to my comment about `node-xmpp` being in alpha, it seems as though it's been in alpha for almost a year, and I've no experienced any problems in using it this far, so maybe worth considering using it despite it's version number.

**Comment by kacy** [comment]
:+1: yeah, i'm having to use a fork as well.

**Comment by jak** [comment]
+1 Please merge! hubot-hipchat can't be installed using node v0.12.2

**Pull request merged**
